[build]
  command = "cd backend && npm install"
  publish = "frontend/dist"
  functions = "backend"

[build.environment]
  NODE_ENV = "production"
  MONGO_URI = "mongodb+srv://bastingg05:gladwin2@bastin0.zvpymix.mongodb.net/docuvault?retryWrites=true&w=majority&appName=Bastin0"
  JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/health"
  status = 200
