services:
  - type: web
    name: docuvault-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: "your-secret-key-here"
    healthCheckPath: /health
    autoDeploy: true
