services:
  # Backend Service
  - type: web
    name: docuvault-v2-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: docuvault-v2-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishDirectory: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://docuvault-v2-backend.onrender.com
    autoDeploy: true
