services:
  # Free Backend Service (Web Service with free tier)
  - type: web
    name: docuvault-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Free Frontend Service (Static Site - always free)
  - type: web
    name: docuvault-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://docuvault-backend.onrender.com
    autoDeploy: true
