services:
  # Combined Backend + Frontend Service
  - type: web
    name: docuvault-v2
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://bastingg05:gladwin2@bastin0.zvpymix.mongodb.net/docuvault-v2?retryWrites=true&w=majority&appName=Bastin0
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
    healthCheckPath: /health
    autoDeploy: true
